/**
 * ═══════════════════════════════════════════════════════════════════
 *  Proxy Executor — Runs translated proxy code in a sandboxed child
 * ═══════════════════════════════════════════════════════════════════
 *
 *  PURPOSE:
 *    Executes the proxy script (generated by translationEngine.ts)
 *    as a child process with resource limits. Captures stdout, stderr,
 *    exit code, and any runtime errors. Produces structured error
 *    reports for Category 2 (logic) bugs.
 *
 *  RESOURCE LIMITS:
 *    On Windows: Uses Job Objects via child process options
 *    On Linux: Uses ulimit / cgroups (basic support in MVP)
 *    In all cases: enforces a timeout (max_runtime_minutes)
 *
 *  USED BY:
 *    - src/vre/index.ts    (full VRE lifecycle)
 *    - src/commands.ts     (vre.translateAndRun command)
 *
 *  ERROR CLASSIFICATION:
 *    After the proxy runs, stderr/exit code is analyzed to classify
 *    errors as Category 1 (hardware) or Category 2 (logic).
 *    Only Category 2 errors generate vre.error.report.json.
 * ═══════════════════════════════════════════════════════════════════
 */

import { spawn, ChildProcess } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';
import { Logger } from '../utils/logger';
import { readVreConfig } from '../utils/fileGenerator';

const LOG_SOURCE = 'ProxyExecutor';

export interface ExecutionResult {
    /** Whether the proxy ran to completion without error */
    success: boolean;
    /** Exit code of the child process */
    exitCode: number | null;
    /** Full stdout captured */
    stdout: string;
    /** Full stderr captured */
    stderr: string;
    /** Duration in milliseconds */
    durationMs: number;
    /** Classified error (if any) */
    error: ProxyError | null;
    /** Whether execution was killed due to timeout */
    timedOut: boolean;
}

export interface ProxyError {
    /** Python/JS error type (e.g., "ZeroDivisionError", "TypeError") */
    errorType: string;
    /** Error message */
    message: string;
    /** File where the error occurred */
    file: string;
    /** Line number */
    line: number | null;
    /** Function name (if parseable) */
    function: string | null;
    /** Full stack trace lines */
    stackTrace: string[];
    /** Error category: 1 = hardware-dependent, 2 = logic (hardware-blind) */
    category: 1 | 2;
    /** Explanation of the category classification */
    categoryNote: string;
}

/** Patterns that indicate Category 1 (hardware-dependent) errors */
const CATEGORY_1_PATTERNS = [
    /CUDA out of memory/i,
    /RuntimeError: .*out of memory/i,
    /MemoryError/i,
    /torch\.cuda\.OutOfMemoryError/i,
    /Resource exhausted/i,
    /OOM/,
    /Cannot allocate memory/i,
    /GPU memory/i,
    /insufficient memory/i,
];

/** Patterns that indicate Category 2 (logic) errors */
const CATEGORY_2_PATTERNS = [
    /ZeroDivisionError/,
    /IndexError/,
    /KeyError/,
    /TypeError/,
    /ValueError/,
    /AttributeError/,
    /NameError/,
    /ImportError/,
    /ModuleNotFoundError/,
    /FileNotFoundError/,
    /SyntaxError/,
    /IndentationError/,
    /UnboundLocalError/,
    /RuntimeError(?!.*memory)/i,
    /AssertionError/,
    /StopIteration/,
    /ReferenceError/,
    /RangeError/,
    /SyntaxError/,
    /URIError/,
];

/**
 * Classify an error as Category 1 (hardware) or Category 2 (logic).
 */
function classifyError(stderr: string): { category: 1 | 2; note: string } {
    for (const pattern of CATEGORY_1_PATTERNS) {
        if (pattern.test(stderr)) {
            return {
                category: 1,
                note: 'Hardware-dependent error — would not occur on the target machine. Not a code bug.',
            };
        }
    }
    return {
        category: 2,
        note: 'Logic error — hardware-blind, will occur on any machine regardless of specs. This is a code bug.',
    };
}

/**
 * Parse a Python traceback from stderr.
 */
function parsePythonTraceback(stderr: string): Partial<ProxyError> {
    const lines = stderr.split('\n');
    const stackTrace: string[] = [];
    let errorType = 'UnknownError';
    let message = '';
    let file: string | null = null;
    let lineNum: number | null = null;
    let func: string | null = null;

    // Find the last exception line
    for (let i = lines.length - 1; i >= 0; i--) {
        const line = lines[i].trim();
        if (line && !line.startsWith('Traceback')) {
            const match = line.match(/^(\w+Error|\w+Exception):\s*(.*)/);
            if (match) {
                errorType = match[1];
                message = match[2];
                break;
            }
        }
    }

    // Parse stack trace entries
    for (const line of lines) {
        const traceMatch = line.match(/File "(.+?)", line (\d+)(?:, in (.+))?/);
        if (traceMatch) {
            stackTrace.push(`${traceMatch[1]} line ${traceMatch[2]}${traceMatch[3] ? ` in ${traceMatch[3]}` : ''}`);
            file = traceMatch[1];
            lineNum = parseInt(traceMatch[2]);
            func = traceMatch[3] || null;
        }
    }

    return { errorType, message, file: file || 'unknown', line: lineNum, function: func, stackTrace };
}

/**
 * Parse a Node.js error from stderr.
 */
function parseNodeError(stderr: string): Partial<ProxyError> {
    const lines = stderr.split('\n');
    const stackTrace: string[] = [];
    let errorType = 'Error';
    let message = '';
    let file: string | null = null;
    let lineNum: number | null = null;
    let func: string | null = null;

    // First line is usually "ErrorType: message"
    for (const line of lines) {
        const errorMatch = line.match(/^(\w+Error|\w+Exception):\s*(.*)/);
        if (errorMatch) {
            errorType = errorMatch[1];
            message = errorMatch[2];
            continue;
        }

        const traceMatch = line.match(/at\s+(.+?)\s+\((.+?):(\d+):\d+\)/);
        if (traceMatch) {
            stackTrace.push(`${traceMatch[2]} line ${traceMatch[3]} in ${traceMatch[1]}`);
            if (!file) {
                file = traceMatch[2];
                lineNum = parseInt(traceMatch[3]);
                func = traceMatch[1];
            }
        }
    }

    return { errorType, message, file: file || 'unknown', line: lineNum, function: func, stackTrace };
}

/**
 * Execute a proxy file and capture the result.
 *
 * @param proxyFilePath  - Absolute path to the proxy script
 * @param workspaceRoot  - Project workspace root
 * @param language        - 'python' or 'node'
 */
export function executeProxy(
    proxyFilePath: string,
    workspaceRoot: string,
    language: 'python' | 'node' = 'python'
): Promise<ExecutionResult> {
    const logger = Logger.getInstance();
    const config = readVreConfig(workspaceRoot);
    const timeoutMs = config.max_runtime_minutes * 60 * 1000;

    logger.info(LOG_SOURCE, `Executing proxy: ${path.basename(proxyFilePath)} (${language})`);
    logger.info(LOG_SOURCE, `  Timeout: ${config.max_runtime_minutes} minutes`);

    return new Promise((resolve) => {
        const startTime = Date.now();
        let stdout = '';
        let stderr = '';
        let timedOut = false;
        let child: ChildProcess;

        const command = language === 'python' ? 'python' : 'node';
        child = spawn(command, [proxyFilePath], {
            cwd: workspaceRoot,
            env: { ...process.env },
            stdio: ['pipe', 'pipe', 'pipe'],
        });

        // Timeout enforcement
        const timeout = setTimeout(() => {
            timedOut = true;
            child.kill('SIGTERM');
            logger.warn(LOG_SOURCE, `Proxy execution timed out after ${config.max_runtime_minutes} minutes`);
        }, timeoutMs);

        child.stdout?.on('data', (data: Buffer) => {
            stdout += data.toString();
        });

        child.stderr?.on('data', (data: Buffer) => {
            stderr += data.toString();
        });

        child.on('close', (exitCode: number | null) => {
            clearTimeout(timeout);
            const durationMs = Date.now() - startTime;

            let error: ProxyError | null = null;

            if (exitCode !== 0 && stderr.trim()) {
                // Parse the error
                const parsed = language === 'python'
                    ? parsePythonTraceback(stderr)
                    : parseNodeError(stderr);

                const classification = classifyError(stderr);

                error = {
                    errorType: parsed.errorType || 'UnknownError',
                    message: parsed.message || stderr.split('\n').pop() || 'Unknown error',
                    file: parsed.file || path.basename(proxyFilePath),
                    line: parsed.line || null,
                    function: parsed.function || null,
                    stackTrace: parsed.stackTrace || [],
                    category: classification.category,
                    categoryNote: classification.note,
                };

                logger.error(LOG_SOURCE, `Proxy error (Category ${error.category}): ${error.errorType}: ${error.message}`);
            }

            const result: ExecutionResult = {
                success: exitCode === 0,
                exitCode,
                stdout,
                stderr,
                durationMs,
                error,
                timedOut,
            };

            if (result.success) {
                logger.info(LOG_SOURCE, `✅ Proxy executed successfully in ${durationMs}ms`);
            }

            resolve(result);
        });

        child.on('error', (err: Error) => {
            clearTimeout(timeout);
            const durationMs = Date.now() - startTime;
            logger.error(LOG_SOURCE, `Failed to spawn proxy process: ${err.message}`);

            resolve({
                success: false,
                exitCode: -1,
                stdout,
                stderr: err.message,
                durationMs,
                error: {
                    errorType: 'SpawnError',
                    message: err.message,
                    file: proxyFilePath,
                    line: null,
                    function: null,
                    stackTrace: [],
                    category: 2,
                    categoryNote: 'Process spawn failure — check if runtime is installed',
                },
                timedOut: false,
            });
        });
    });
}
